### ISSUE TITLE
provide working config examples

### ISSUE THREAD

**Issue by dfong** [packet-labs/google-anthos#116]
there could be a directory of concrete configurations that are known to work.  these would be helpful for users, and could be used in automated tests.  it would also help to have separate files for private vars vs non-private vars, as suggested in issue 115.  if this is done, then only the non-private side would be shared, of course.

**Comment by displague** [comment]
In a terraform module, these examples should be provided in `examples/name-of-example/main.tf`

It would be interesting to use one of these examples for testing, rather than using the `git pull` for testing.  Doing so will ensure that the root module behavior is functional.

This is something to consider after #125.
