### ISSUE TITLE
Make dnsmasq changes more resilient

### ISSUE THREAD

**Issue by matthewkrupnik** [packet-labs/google-anthos#22]
Maybe it's too much of a one off, but I ran into an issue where terraform exited with an error when running `33-anthos-deploy-admin-workstation.tf`. And when I restart things break pretty bad because `replace_tf_vars.py` ran before the failure and added an entry in `dhcp.conf` for admin workstation. When I re-run terraform it executes the script again, which adds the line again and then dnsmasq doesn't start anymore because it sees two reservations for the same IP. And then entire ESXi cluster starts to fall apart because hosts are added by FQDN to vCenter and once dnsmasq is down it can no longer resolve the names. A quick check to see if the last line in the file is the same as the line being added before adding it would make the script more resilient.

**Comment by c0dyhi11** [comment]
Hey @matthewkrupnik,

Thanks for creating this issue.

I agree this should be more resilient and idempotent. We should search the whole file for the IP because it might not be the last line either... This entire playbook should be looked at for issues like this. My recommendation is a `terraform destroy --auto-approve && terraform apply --auto-approve` for issues like this for now (I know it's not ideal, but is your safest bet).
Let's keep this issue open and maybe someone in the community will take up this task and make it more resilient.

**Comment by boredabdel** [comment]
I can take this one. I think it's  a general thing that applies to every script we have in the codebase, we need a failsafe mechanism for re-running scripts upon Terraform failure.
