### ISSUE TITLE
Support for different datastore types

### ISSUE THREAD

**Issue by matthewkrupnik** [packet-labs/google-anthos#23]
With vSAN having issues when selecting different instance types and some instance types having very limited storage I think it's a good idea to add support for NFS. I am currently doing this by hand.. creating a new storage volume, attaching it to the router machine and hosting NFS server allows for a datastore of any size.

For reference, here's the doc for attaching storage volume to machine: https://www.packet.com/resources/guides/elastic-block-storage/

**Comment by c0dyhi11** [comment]
Hey @matthewkrupnik,

That's a great idea. I'd love to get you involved in this project to help implement some of this. We could add a flag for `deploy_nfs=true` and if it's true we'd then have a parameter for the size of volume.

We are currently building single node support which will allow you to use the local disk instead of vSan. (I'm testing this as I write this)

Let me know if you'd like to help out!

Thank you,
Cody Hill

**Comment by boredabdel** [comment]
Does packet.com have a managed NFS offering @c0dyhi11 ? or this should be implemented with a simple single NFS server on Linux ?
