### ISSUE TITLE
Working with n2.xlarges

### ISSUE THREAD

**Issue by paemason** [packet-labs/google-anthos#25]
I attempted to do an ESXi single server deployment on an n2.xlarge however hit an issue with the api call to move from layer3 to hybrid.

`Error: Failed to convert device eae44273-c7e1-404e-aa6d-4284445545c3 from layer3 to hybrid. New type was layer3`

**Comment by c0dyhi11** [comment]
@t0mk Can you please take a look at getting Hybrid mode to work on n2.xlarge hosts/
https://github.com/packet-labs/google-anthos/blob/764f580afe90e6ae6eb7819fd36fe6bd6a6d4059/04-esx-hosts.tf#L10

**Comment by t0mk** [comment]
hi, I will take a look today. There are more network cards, so the n2 must be handled a bit differently. This is related comment:
https://github.com/terraform-providers/terraform-provider-packet/issues/224#issuecomment-593923444

**Comment by t0mk** [comment]
Hey, this should be fixed in provider version 2.8.0 by https://github.com/terraform-providers/terraform-provider-packet/pull/225

**Comment by displague** [comment]
This issue is ongoing, as @paemason reported in [Packet Slack #google-anthos](https://packetcommunity.slack.com/archives/CU7HC3RJP/p1594321185283700).  

> I received this error using 2.10.0 despite the portal telling me that the device is in Hybrid mode:
> ```
> packet_port_vlan_attachment.esxi_priv_vlan_attach[3]: Creation complete after 2m13s [id=184e231b-140a-443b-a0af-ed1e74ee1eb3:13b08e88-f90c-44d6-9b07-9e3b6bf5aa25]
> Error: Failed to convert device 5babd026-68f0-4d4f-a58b-8f67cf363f0b from layer3 to hybrid. New type was layer3
> ```

I'm going to start adding tests in packngo and terraform-provider-packet to verify that these functions are behaving predictably and expectedly.  The problematic states @t0mk reported from the manual testing at https://github.com/terraform-providers/terraform-provider-packet/issues/224#issuecomment-593923444 could be included in the Hashicorp E2E tests for the provider.  I'd also like to run these tests now to verify that the API is behaving as expected for these machine types.

**Comment by t0mk** [comment]
@displague I keep this in mind, I've just managed to run the vmware device again, and I will try to debug this today.

**Comment by t0mk** [comment]
@displague This happens with n2.large?

**Comment by displague** [comment]
I believe that with the update to the v1.1 Equinix Metal Terraform provider, this error should no longer occur.

Please comment for a reopen if you (anyone) finds otherwise.
